pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/AmartuvshinG/CalculatorApp', credentialsId: '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'
            }
        }

        stage('Compile') {
            steps {

                sh 'javac -d bin src/*.java'
            }
        }

        stage('Run Tests') {
            steps {

                sh 'java -cp "bin:lib/*" org.junit.runner.JUnitCore TestClassName'
            }
        }
    }

    post {
        always {

            archiveArtifacts artifacts: 'bin/**/*.class', allowEmptyArchive: true
        }
        failure {
            mail to: 'ganzorig001@gannon.edu',
                 subject: "Test Failed: ${currentBuild.fullDisplayName}",
                 body: "The build failed. Please check the Jenkins job."
        }
    }
}
